version: '2'

services:
  kibana:
    image: kibana:7.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601

  logstash:
    image: logstash:7.6.2
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
      # /usr/share/logstash/config
    ports:
      - 5000:5000 # Syslog
      - 5044:5044 # Beats

  elasticsearch:
    image: elasticsearch:7.6.2
    cap_add:
      - IPC_LOCK
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300

volumes:
  esdata1: